title: PXR Platform
description: Documentation and tools for PXR template
remote_theme: just-the-docs/just-the-docs
url: https://tinfoika.github.io/PXRPlatform
baseurl: "/PXRPlatform"

aux_links:
  "PXR Platform on GitHub":
    - "https://github.com/TinFoiKa/PXRPlatform"

# Enable search
search_enabled: true

# Enable dark mode
color_scheme: pxtheme

# Build settings
markdown: kramdown
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
